INSERT INTO USER (USER_ID, USER_PASSWORD, USER_NAME, USER_EMAIL) VALUES ('a', 'b', 'c', 'd@naver.com');

INSERT INTO USER (USER_ID, USER_PASSWORD, USER_NAME, USER_EMAIL) VALUES ('aa', 'bb', 'cc', 'dd@naver.com');

INSERT INTO USER (USER_ID, USER_PASSWORD, USER_NAME, USER_EMAIL) VALUES ('aaa', 'bbb', 'ccc', 'ddd@naver.com');